#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1636327607                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your precious metals with ease.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Precious Metals Manager                                
your_link                                 :                    
your_city                                 : Spain                                
email_address                             : sergio@preciousmetalsmanager.com
facebook_username                         : 100084229184603                                         
instagram_username                        : 
x_username                                : metalsmanager
github_username                           : 
youtube_username                          : PreciousMetalsManager
linkedin_username                         : 



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1
topbar_title_color                        : "#27201d"

cover_image                               :                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#f0f1f2"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f0f1f2"

link_color                                : "#1d63ea"

app_title_color                           : "#00334F"
app_price_color                           : "#00334F"
app_description_color                     : "#00334F"

feature_title_color                       : "#27201d"
feature_text_color                        : "#007aff"
feature_note_color                        : "#666666"

social_icons_foreground_color             : "#27201d"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#ffffff"
footer_background_color                   : "#00334F"


plugins:
  - jekyll-seo-tag # Adds all the important SEO meta tags by default.
  - jekyll-sitemap # Adds sitemap to the website at /sitemap.xml
  - jekyll-include-cache   # use include_cached instead of include


# Google Tag
# The Analytics tag is a snippet of JavaScript that collects and sends data to Analytics from a website.
google-tag: G-WXNPC82QM4

# This defines how the URLs should look like.
permalink: /blog/:title/

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed
  sass_dir: /assets/css/_sass

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
